export const countries = [
  { "name": "Afghanistan", "dialCode": "+93", "alpha2": "AF" },
  { "name": "Albania", "dialCode": "+355", "alpha2": "AL" },
  { "name": "Algeria", "dialCode": "+213", "alpha2": "DZ" },
  { "name": "American Samoa", "dialCode": "+1684", "alpha2": "AS" },
  { "name": "Andorra", "dialCode": "+376", "alpha2": "AD" },
  { "name": "Angola", "dialCode": "+244", "alpha2": "AO" },
  { "name": "Anguilla", "dialCode": "+1264", "alpha2": "AI" },
  { "name": "Antigua and Barbuda", "dialCode": "+1268", "alpha2": "AG" },
  { "name": "Argentina", "dialCode": "+54", "alpha2": "AR" },
  { "name": "Armenia", "dialCode": "+374", "alpha2": "AM" },
  { "name": "Aruba", "dialCode": "+297", "alpha2": "AW" },
  { "name": "Australia", "dialCode": "+61", "alpha2": "AU" },
  { "name": "Austria", "dialCode": "+43", "alpha2": "AT" },
  { "name": "Azerbaijan", "dialCode": "+994", "alpha2": "AZ" },
  { "name": "Bahamas", "dialCode": "+1242", "alpha2": "BS" },
  { "name": "Bahrain", "dialCode": "+973", "alpha2": "BH" },
  { "name": "Bangladesh", "dialCode": "+880", "alpha2": "BD" },
  { "name": "Barbados", "dialCode": "+1246", "alpha2": "BB" },
  { "name": "Belarus", "dialCode": "+375", "alpha2": "BY" },
  { "name": "Belgium", "dialCode": "+32", "alpha2": "BE" },
  { "name": "Belize", "dialCode": "+501", "alpha2": "BZ" },
  { "name": "Benin", "dialCode": "+229", "alpha2": "BJ" },
  { "name": "Bermuda", "dialCode": "+1441", "alpha2": "BM" },
  { "name": "Bhutan", "dialCode": "+975", "alpha2": "BT" },
  { "name": "Bolivia", "dialCode": "+591", "alpha2": "BO" },
  { "name": "Bosnia and Herzegovina", "dialCode": "+387", "alpha2": "BA" },
  { "name": "Botswana", "dialCode": "+267", "alpha2": "BW" },
  { "name": "Brazil", "dialCode": "+55", "alpha2": "BR" },
  { "name": "British Indian Ocean Territory", "dialCode": "+246", "alpha2": "IO" },
  { "name": "Brunei Darussalam", "dialCode": "+673", "alpha2": "BN" },
  { "name": "Bulgaria", "dialCode": "+359", "alpha2": "BG" },
  { "name": "Burkina Faso", "dialCode": "+226", "alpha2": "BF" },
  { "name": "Burundi", "dialCode": "+257", "alpha2": "BI" },
  { "name": "Cambodia", "dialCode": "+855", "alpha2": "KH" },
  { "name": "Cameroon", "dialCode": "+237", "alpha2": "CM" },
  { "name": "Canada", "dialCode": "+1", "alpha2": "CA" },
  { "name": "Cape Verde", "dialCode": "+238", "alpha2": "CV" },
  { "name": "Cayman Islands", "dialCode": "+1345", "alpha2": "KY" },
  { "name": "Central African Republic", "dialCode": "+236", "alpha2": "CF" },
  { "name": "Chad", "dialCode": "+235", "alpha2": "TD" },
  { "name": "Chile", "dialCode": "+56", "alpha2": "CL" },
  { "name": "China", "dialCode": "+86", "alpha2": "CN" },
  { "name": "Christmas Island", "dialCode": "+61", "alpha2": "CX" },
  { "name": "Cocos (Keeling) Islands", "dialCode": "+61", "alpha2": "CC" },
  { "name": "Colombia", "dialCode": "+57", "alpha2": "CO" },
  { "name": "Comoros", "dialCode": "+269", "alpha2": "KM" },
  { "name": "Congo", "dialCode": "+242", "alpha2": "CG" },
  { "name": "Congo, The Democratic Republic of the", "dialCode": "+243", "alpha2": "CD" },
  { "name": "Cook Islands", "dialCode": "+682", "alpha2": "CK" },
  { "name": "Costa Rica", "dialCode": "+506", "alpha2": "CR" },
  { "name": "Cote d'Ivoire", "dialCode": "+225", "alpha2": "CI" },
  { "name": "Croatia", "dialCode": "+385", "alpha2": "HR" },
  { "name": "Cuba", "dialCode": "+53", "alpha2": "CU" },
  { "name": "Cyprus", "dialCode": "+357", "alpha2": "CY" },
  { "name": "Czech Republic", "dialCode": "+420", "alpha2": "CZ" },
  { "name": "Denmark", "dialCode": "+45", "alpha2": "DK" },
  { "name": "Djibouti", "dialCode": "+253", "alpha2": "DJ" },
  { "name": "Dominica", "dialCode": "+1767", "alpha2": "DM" },
  { "name": "Dominican Republic", "dialCode": "+1849", "alpha2": "DO" },
  { "name": "Ecuador", "dialCode": "+593", "alpha2": "EC" },
  { "name": "Egypt", "dialCode": "+20", "alpha2": "EG" },
  { "name": "El Salvador", "dialCode": "+503", "alpha2": "SV" },
  { "name": "Equatorial Guinea", "dialCode": "+240", "alpha2": "GQ" },
  { "name": "Eritrea", "dialCode": "+291", "alpha2": "ER" },
  { "name": "Estonia", "dialCode": "+372", "alpha2": "EE" },
  { "name": "Ethiopia", "dialCode": "+251", "alpha2": "ET" },
  { "name": "Falkland Islands (Malvinas)", "dialCode": "+500", "alpha2": "FK" },
  { "name": "Faroe Islands", "dialCode": "+298", "alpha2": "FO" },
  { "name": "Fiji", "dialCode": "+679", "alpha2": "FJ" },
  { "name": "Finland", "dialCode": "+358", "alpha2": "FI" },
  { "name": "France", "dialCode": "+33", "alpha2": "FR" },
  { "name": "French Guiana", "dialCode": "+594", "alpha2": "GF" },
  { "name": "French Polynesia", "dialCode": "+689", "alpha2": "PF" },
  { "name": "Gabon", "dialCode": "+241", "alpha2": "GA" },
  { "name": "Gambia", "dialCode": "+220", "alpha2": "GM" },
  { "name": "Georgia", "dialCode": "+995", "alpha2": "GE" },
  { "name": "Germany", "dialCode": "+49", "alpha2": "DE" },
  { "name": "Ghana", "dialCode": "+233", "alpha2": "GH" },
  { "name": "Gibraltar", "dialCode": "+350", "alpha2": "GI" },
  { "name": "Greece", "dialCode": "+30", "alpha2": "GR" },
  { "name": "Greenland", "dialCode": "+299", "alpha2": "GL" },
  { "name": "Grenada", "dialCode": "+1473", "alpha2": "GD" },
  { "name": "Guadeloupe", "dialCode": "+590", "alpha2": "GP" },
  { "name": "Guam", "dialCode": "+1671", "alpha2": "GU" },
  { "name": "Guatemala", "dialCode": "+502", "alpha2": "GT" },
  { "name": "Guernsey", "dialCode": "+44", "alpha2": "GG" },
  { "name": "Guinea", "dialCode": "+224", "alpha2": "GN" },
  { "name": "Guinea-Bissau", "dialCode": "+245", "alpha2": "GW" },
  { "name": "Guyana", "dialCode": "+592", "alpha2": "GY" },
  { "name": "Haiti", "dialCode": "+509", "alpha2": "HT" },
  { "name": "Holy See (Vatican City State)", "dialCode": "+379", "alpha2": "VA" },
  { "name": "Honduras", "dialCode": "+504", "alpha2": "HN" },
  { "name": "Hong Kong", "dialCode": "+852", "alpha2": "HK" },
  { "name": "Hungary", "dialCode": "+36", "alpha2": "HU" },
  { "name": "Iceland", "dialCode": "+354", "alpha2": "IS" },
  { "name": "India", "dialCode": "+91", "alpha2": "IN" },
  { "name": "Indonesia", "dialCode": "+62", "alpha2": "ID" },
  { "name": "Iran, Islamic Republic of", "dialCode": "+98", "alpha2": "IR" },
  { "name": "Iraq", "dialCode": "+964", "alpha2": "IQ" },
  { "name": "Ireland", "dialCode": "+353", "alpha2": "IE" },
  { "name": "Isle of Man", "dialCode": "+44", "alpha2": "IM" },
  { "name": "Israel", "dialCode": "+972", "alpha2": "IL" },
  { "name": "Italy", "dial_code": "+39", "alpha2": "IT" },
  { "name": "Jamaica", "dialCode": "+1876", "alpha2": "JM" },
  { "name": "Japan", "dialCode": "+81", "alpha2": "JP" },
  { "name": "Jersey", "dialCode": "+44", "alpha2": "JE" },
  { "name": "Jordan", "dialCode": "+962", "alpha2": "JO" },
  { "name": "Kazakhstan", "dialCode": "+7", "alpha2": "KZ" },
  { "name": "Kenya", "dialCode": "+254", "alpha2": "KE" },
  { "name": "Kiribati", "dialCode": "+686", "alpha2": "KI" },
  { "name": "Korea, Democratic People's Republic of", "dialCode": "+850", "alpha2": "KP" },
  { "name": "Korea, Republic of", "dialCode": "+82", "alpha2": "KR" },
  { "name": "Kuwait", "dialCode": "+965", "alpha2": "KW" },
  { "name": "Kyrgyzstan", "dialCode": "+996", "alpha2": "KG" },
  { "name": "Lao People's Democratic Republic", "dialCode": "+856", "alpha2": "LA" },
  { "name": "Latvia", "dialCode": "+371", "alpha2": "LV" },
  { "name": "Lebanon", "dialCode": "+961", "alpha2": "LB" },
  { "name": "Lesotho", "dialCode": "+266", "alpha2": "LS" },
  { "name": "Liberia", "dialCode": "+231", "alpha2": "LR" },
  { "name": "Libyan Arab Jamahiriya", "dialCode": "+218", "alpha2": "LY" },
  { "name": "Liechtenstein", "dialCode": "+423", "alpha2": "LI" },
  { "name": "Lithuania", "dialCode": "+370", "alpha2": "LT" },
  { "name": "Luxembourg", "dialCode": "+352", "alpha2": "LU" },
  { "name": "Macao", "dialCode": "+853", "alpha2": "MO" },
  { "name": "Macedonia, The Former Yugoslav Republic of", "dialCode": "+389", "alpha2": "MK" },
  { "name": "Madagascar", "dialCode": "+261", "alpha2": "MG" },
  { "name": "Malawi", "dialCode": "+265", "alpha2": "MW" },
  { "name": "Malaysia", "dialCode": "+60", "alpha2": "MY" },
  { "name": "Maldives", "dialCode": "+960", "alpha2": "MV" },
  { "name": "Mali", "dialCode": "+223", "alpha2": "ML" },
  { "name": "Malta", "dialCode": "+356", "alpha2": "MT" },
  { "name": "Marshall Islands", "dialCode": "+692", "alpha2": "MH" },
  { "name": "Martinique", "dialCode": "+596", "alpha2": "MQ" },
  { "name": "Mauritania", "dialCode": "+222", "alpha2": "MR" },
  { "name": "Mauritius", "dialCode": "+230", "alpha2": "MU" },
  { "name": "Mayotte", "dialCode": "+262", "alpha2": "YT" },
  { "name": "Mexico", "dialCode": "+52", "alpha2": "MX" },
  { "name": "Micronesia, Federated States of", "dialCode": "+691", "alpha2": "FM" },
  { "name": "Moldova, Republic of", "dialCode": "+373", "alpha2": "MD" },
  { "name": "Monaco", "dialCode": "+377", "alpha2": "MC" },
  { "name": "Mongolia", "dialCode": "+976", "alpha2": "MN" },
  { "name": "Montenegro", "dialCode": "+382", "alpha2": "ME" },
  { "name": "Montserrat", "dialCode": "+1664", "alpha2": "MS" },
  { "name": "Morocco", "dialCode": "+212", "alpha2": "MA" },
  { "name": "Mozambique", "dialCode": "+258", "alpha2": "MZ" },
  { "name": "Myanmar", "dialCode": "+95", "alpha2": "MM" },
  { "name": "Namibia", "dialCode": "+264", "alpha2": "NA" },
  { "name": "Nauru", "dialCode": "+674", "alpha2": "NR" },
  { "name": "Nepal", "dialCode": "+977", "alpha2": "NP" },
  { "name": "Netherlands", "dialCode": "+31", "alpha2": "NL" },
  { "name": "Netherlands Antilles", "dialCode": "+599", "alpha2": "AN" },
  { "name": "New Caledonia", "dialCode": "+687", "alpha2": "NC" },
  { "name": "New Zealand", "dialCode": "+64", "alpha2": "NZ" },
  { "name": "Nicaragua", "dialCode": "+505", "alpha2": "NI" },
  { "name": "Niger", "dialCode": "+227", "alpha2": "NE" },
  { "name": "Nigeria", "dialCode": "+234", "alpha2": "NG" },
  { "name": "Niue", "dialCode": "+683", "alpha2": "NU" },
  { "name": "Norfolk Island", "dialCode": "+672", "alpha2": "NF" },
  { "name": "Northern Mariana Islands", "dialCode": "+1670", "alpha2": "MP" },
  { "name": "Norway", "dialCode": "+47", "alpha2": "NO" },
  { "name": "Oman", "dialCode": "+968", "alpha2": "OM" },
  { "name": "Pakistan", "dialCode": "+92", "alpha2": "PK" },
  { "name": "Palau", "dialCode": "+680", "alpha2": "PW" },
  { "name": "Palestinian Territory, Occupied", "dialCode": "+970", "alpha2": "PS" },
  { "name": "Panama", "dialCode": "+507", "alpha2": "PA" },
  { "name": "Papua New Guinea", "dialCode": "+675", "alpha2": "PG" },
  { "name": "Paraguay", "dialCode": "+595", "alpha2": "PY" },
  { "name": "Peru", "dialCode": "+51", "alpha2": "PE" },
  { "name": "Philippines", "dialCode": "+63", "alpha2": "PH" },
  { "name": "Pitcairn", "dialCode": "+870", "alpha2": "PN" },
  { "name": "Poland", "dialCode": "+48", "alpha2": "PL" },
  { "name": "Portugal", "dialCode": "+351", "alpha2": "PT" },
  { "name": "Puerto Rico", "dialCode": "+1939", "alpha2": "PR" },
  { "name": "Qatar", "dialCode": "+974", "alpha2": "QA" },
  { "name": "Reunion", "dialCode": "+262", "alpha2": "RE" },
  { "name": "Romania", "dialCode": "+40", "alpha2": "RO" },
  { "name": "Russian Federation", "dialCode": "+7", "alpha2": "RU" },
  { "name": "Rwanda", "dialCode": "+250", "alpha2": "RW" },
  { "name": "Saint Barthelemy", "dialCode": "+590", "alpha2": "BL" },
  { "name": "Saint Helena, Ascension and Tristan Da Cunha", "dialCode": "+290", "alpha2": "SH" },
  { "name": "Saint Kitts and Nevis", "dialCode": "+1869", "alpha2": "KN" },
  { "name": "Saint Lucia", "dialCode": "+1758", "alpha2": "LC" },
  { "name": "Saint Martin", "dialCode": "+590", "alpha2": "MF" },
  { "name": "Saint Pierre and Miquelon", "dialCode": "+508", "alpha2": "PM" },
  { "name": "Saint Vincent and the Grenadines", "dialCode": "+1784", "alpha2": "VC" },
  { "name": "Samoa", "dialCode": "+685", "alpha2": "WS" },
  { "name": "San Marino", "dialCode": "+378", "alpha2": "SM" },
  { "name": "Sao Tome and Principe", "dialCode": "+239", "alpha2": "ST" },
  { "name": "Saudi Arabia", "dialCode": "+966", "alpha2": "SA" },
  { "name": "Senegal", "dialCode": "+221", "alpha2": "SN" },
  { "name": "Serbia", "dialCode": "+381", "alpha2": "RS" },
  { "name": "Seychelles", "dialCode": "+248", "alpha2": "SC" },
  { "name": "Sierra Leone", "dialCode": "+232", "alpha2": "SL" },
  { "name": "Singapore", "dialCode": "+65", "alpha2": "SG" },
  { "name": "Slovakia", "dialCode": "+421", "alpha2": "SK" },
  { "name": "Slovenia", "dialCode": "+386", "alpha2": "SI" },
  { "name": "Solomon Islands", "dialCode": "+677", "alpha2": "SB" },
  { "name": "Somalia", "dialCode": "+252", "alpha2": "SO" },
  { "name": "South Africa", "dialCode": "+27", "alpha2": "ZA" },
  { "name": "South Georgia and the South Sandwich Islands", "dialCode": "+500", "alpha2": "GS" },
  { "name": "Spain", "dialCode": "+34", "alpha2": "ES" },
  { "name": "Sri Lanka", "dialCode": "+94", "alpha2": "LK" },
  { "name": "Sudan", "dialCode": "+249", "alpha2": "SD" },
  { "name": "Suriname", "dialCode": "+597", "alpha2": "SR" },
  { "name": "Svalbard and Jan Mayen", "dialCode": "+47", "alpha2": "SJ" },
  { "name": "Swaziland", "dialCode": "+268", "alpha2": "SZ" },
  { "name": "Sweden", "dialCode": "+46", "alpha2": "SE" },
  { "name": "Switzerland", "dialCode": "+41", "alpha2": "CH" },
  { "name": "Syrian Arab Republic", "dialCode": "+963", "alpha2": "SY" },
  { "name": "Taiwan, Province of China", "dialCode": "+886", "alpha2": "TW" },
  { "name": "Tajikistan", "dialCode": "+992", "alpha2": "TJ" },
  { "name": "Tanzania, United Republic of", "dialCode": "+255", "alpha2": "TZ" },
  { "name": "Thailand", "dialCode": "+66", "alpha2": "TH" },
  { "name": "Timor-Leste", "dialCode": "+670", "alpha2": "TL" },
  { "name": "Togo", "dialCode": "+228", "alpha2": "TG" },
  { "name": "Tokelau", "dialCode": "+690", "alpha2": "TK" },
  { "name": "Tonga", "dialCode": "+676", "alpha2": "TO" },
  { "name": "Trinidad and Tobago", "dialCode": "+1868", "alpha2": "TT" },
  { "name": "Tunisia", "dialCode": "+216", "alpha2": "TN" },
  { "name": "Turkey", "dialCode": "+90", "alpha2": "TR" },
  { "name": "Turkmenistan", "dialCode": "+993", "alpha2": "TM" },
  { "name": "Turks and Caicos Islands", "dialCode": "+1649", "alpha2": "TC" },
  { "name": "Tuvalu", "dialCode": "+688", "alpha2": "TV" },
  { "name": "Uganda", "dialCode": "+256", "alpha2": "UG" },
  { "name": "Ukraine", "dialCode": "+380", "alpha2": "UA" },
  { "name": "United Arab Emirates", "dialCode": "+971", "alpha2": "AE" },
  { "name": "United Kingdom", "dialCode": "+44", "alpha2": "GB" },
  { "name": "United States", "dialCode": "+1", "alpha2": "US" },
  { "name": "Uruguay", "dialCode": "+598", "alpha2": "UY" },
  { "name": "Uzbekistan", "dialCode": "+998", "alpha2": "UZ" },
  { "name": "Vanuatu", "dialCode": "+678", "alpha2": "VU" },
  { "name": "Venezuela, Bolivarian Republic of", "dialCode": "+58", "alpha2": "VE" },
  { "name": "Viet Nam", "dialCode": "+84", "alpha2": "VN" },
  { "name": "Virgin Islands, British", "dialCode": "+1284", "alpha2": "VG" },
  { "name": "Virgin Islands, U.S.", "dialCode": "+1340", "alpha2": "VI" },
  { "name": "Wallis and Futuna", "dialCode": "+681", "alpha2": "WF" },
  { "name": "Yemen", "dialCode": "+967", "alpha2": "YE" },
  { "name": "Zambia", "dialCode": "+260", "alpha2": "ZM" },
  { "name": "Zimbabwe", "dialCode": "+263", "alpha2": "ZW" }
]